# Generated by Django 5.0.1 on 2025-07-02 01:29

import apps.feeds.domain.entities.post_file
import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField(max_length=500)),
                ('is_multiple_choice', models.BooleanField(default=False)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('allows_other', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Poll',
                'verbose_name_plural': 'Polls',
                'db_table': 'feed_polls',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='Contenido del post')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True, verbose_name='Vector de embedding para recomendaciones')),
                ('likes_count', models.IntegerField(default=0, verbose_name='Número de likes')),
                ('comments_count', models.IntegerField(default=0, verbose_name='Número de comentarios')),
                ('views_count', models.IntegerField(default=0, verbose_name='Número de visualizaciones')),
                ('shares_count', models.IntegerField(default=0, verbose_name='Número de compartidos')),
                ('engagement_score', models.FloatField(default=0.0, verbose_name='Score de engagement')),
                ('is_public', models.BooleanField(default=True, verbose_name='Post público')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Post fijado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tags del post')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadatos adicionales')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_posts', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('poll', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='feeds.poll', verbose_name='Encuesta del post')),
            ],
            options={
                'verbose_name': 'Post del Feed',
                'verbose_name_plural': 'Posts del Feed',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=200)),
                ('votes_count', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='feeds.poll')),
            ],
            options={
                'verbose_name': 'Poll Option',
                'verbose_name_plural': 'Poll Options',
                'db_table': 'feed_poll_options',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='feeds.polloption')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='feeds.poll')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Poll Vote',
                'verbose_name_plural': 'Poll Votes',
                'db_table': 'feed_poll_votes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=apps.feeds.domain.entities.post_file.get_post_file_path, verbose_name='Archivo')),
                ('file_type', models.CharField(choices=[('image', 'Imagen'), ('document', 'Documento'), ('video', 'Video'), ('audio', 'Audio'), ('other', 'Otro')], max_length=20, verbose_name='Tipo de archivo')),
                ('file_size', models.BigIntegerField(verbose_name='Tamaño del archivo en bytes')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Nombre original del archivo')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='Ancho (para imágenes)')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Alto (para imágenes)')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Texto alternativo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_files', to='feeds.feedpost', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Archivo de Post',
                'verbose_name_plural': 'Archivos de Posts',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='Contenido del comentario')),
                ('likes_count', models.IntegerField(default=0, verbose_name='Número de likes')),
                ('replies_count', models.IntegerField(default=0, verbose_name='Número de respuestas')),
                ('is_edited', models.BooleanField(default=False, verbose_name='Comentario editado')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Comentario eliminado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadatos adicionales')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_comments', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='feeds.comment', verbose_name='Comentario padre')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='feeds.feedpost', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['post', 'created_at'], name='feeds_comme_post_id_d0cc2a_idx'), models.Index(fields=['parent_comment', 'created_at'], name='feeds_comme_parent__83ba9a_idx'), models.Index(fields=['author', '-created_at'], name='feeds_comme_author__e3556e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de like')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_given', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Like',
                'verbose_name_plural': 'Likes',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='feeds_like_content_3a0a6e_idx'), models.Index(fields=['user', '-created_at'], name='feeds_like_user_id_066e8a_idx')],
                'unique_together': {('user', 'content_type', 'object_id')},
            },
        ),
        migrations.AddIndex(
            model_name='feedpost',
            index=models.Index(fields=['-created_at'], name='feeds_feedp_created_1d2dfd_idx'),
        ),
        migrations.AddIndex(
            model_name='feedpost',
            index=models.Index(fields=['-engagement_score'], name='feeds_feedp_engagem_dca4e8_idx'),
        ),
        migrations.AddIndex(
            model_name='feedpost',
            index=models.Index(fields=['author', '-created_at'], name='feeds_feedp_author__d5088f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='polloption',
            unique_together={('poll', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='pollvote',
            unique_together={('user', 'poll', 'option')},
        ),
    ]
