# Generated by Django 5.0.1 on 2025-07-02 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_add_poll_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedpost',
            name='poll',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='feeds.poll', verbose_name='Encuesta del post'),
        ),
    ]
