# Generated by Django 5.0.1 on 2025-07-02 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_alter_feedpost_poll'),
    ]

    operations = [
    ]
