# Generated by Django 5.0.1 on 2025-07-03 21:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_auto_20250702_0223'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='feedpost',
            index=models.Index(fields=['-engagement_score', '-created_at'], name='trending_idx'),
        ),
    ]
