# Generated by Django 5.0.1 on 2025-07-03 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='status',
        ),
    ]
