from django.db import migrations, models
import django.db.models.deletion


def migrate_job_interaction_table(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS jobs_jobinteraction (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_identity_id varchar(64) NOT NULL,
                user_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
                job_id bigint NOT NULL
                    REFERENCES jobs(id) DEFERRABLE INITIALLY DEFERRED,
                interaction_type varchar(20) NOT NULL,
                timestamp timestamp with time zone NOT NULL,
                metadata jsonb NOT NULL DEFAULT '{}'::jsonb
            );
            """
        )
        cursor.execute(
            """
            ALTER TABLE jobs_jobinteraction
                ADD COLUMN IF NOT EXISTS user_identity_id varchar(64);
            ALTER TABLE jobs_jobinteraction
                ADD COLUMN IF NOT EXISTS user_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb;
            """
        )
        cursor.execute(
            """
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_schema = 'public'
                      AND table_name = 'jobs_jobinteraction'
                      AND column_name = 'user_id'
                ) THEN
                    UPDATE jobs_jobinteraction ji
                    SET
                        user_identity_id = COALESCE(ji.user_identity_id, ji.user_id),
                        user_snapshot = jsonb_build_object(
                            'id', u.id,
                            'username', COALESCE(u.username, ''),
                            'first_name', COALESCE(u.first_name, ''),
                            'last_name', COALESCE(u.last_name, ''),
                            'profile_picture', COALESCE(u.profile_picture, '')
                        )
                    FROM users u
                    WHERE ji.user_id = u.id;

                    UPDATE jobs_jobinteraction
                    SET
                        user_identity_id = COALESCE(user_identity_id, user_id),
                        user_snapshot = COALESCE(user_snapshot, '{}'::jsonb)
                    WHERE user_identity_id IS NULL;
                END IF;
            END $$;
            """
        )
        cursor.execute(
            """
            DO $$
            DECLARE
                r record;
            BEGIN
                FOR r IN
                    SELECT conname
                    FROM pg_constraint
                    WHERE conrelid = 'jobs_jobinteraction'::regclass
                      AND (
                        conname LIKE '%user_id%'
                        OR conname LIKE '%user_identity_id%'
                      )
                LOOP
                    EXECUTE format(
                        'ALTER TABLE jobs_jobinteraction DROP CONSTRAINT IF EXISTS %I',
                        r.conname
                    );
                END LOOP;
            END $$;
            """
        )
        cursor.execute(
            """
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_schema = 'public'
                      AND table_name = 'jobs_jobinteraction'
                      AND column_name = 'user_id'
                ) THEN
                    ALTER TABLE jobs_jobinteraction DROP COLUMN user_id CASCADE;
                END IF;
            END $$;
            """
        )
        cursor.execute(
            """
            ALTER TABLE jobs_jobinteraction
                ALTER COLUMN user_identity_id SET NOT NULL;
            ALTER TABLE jobs_jobinteraction
                ALTER COLUMN user_snapshot DROP DEFAULT;

            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conrelid = 'jobs_jobinteraction'::regclass
                      AND conname = 'jobs_jobinteraction_identity_job_type_uniq'
                ) THEN
                    ALTER TABLE jobs_jobinteraction
                    ADD CONSTRAINT jobs_jobinteraction_identity_job_type_uniq
                    UNIQUE (user_identity_id, job_id, interaction_type);
                END IF;
            END $$;

            CREATE INDEX IF NOT EXISTS jobs_jobint_user_ident_idx
                ON jobs_jobinteraction (user_identity_id, timestamp);
            CREATE INDEX IF NOT EXISTS jobs_jobint_job_type_idx
                ON jobs_jobinteraction (job_id, interaction_type);
            CREATE INDEX IF NOT EXISTS jobs_jobint_ts_idx
                ON jobs_jobinteraction (timestamp);
            CREATE INDEX IF NOT EXISTS jobs_jobint_user_ident_only_idx
                ON jobs_jobinteraction (user_identity_id);
            """
        )


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0004_external_identity_refs"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(migrate_job_interaction_table, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="JobInteraction",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("user_identity_id", models.CharField(db_index=True, max_length=64, verbose_name="ID externo del usuario")),
                        ("user_snapshot", models.JSONField(blank=True, default=dict, verbose_name="Snapshot del usuario")),
                        ("interaction_type", models.CharField(choices=[("view", "Vista"), ("application", "Aplicacion"), ("save", "Guardado"), ("share", "Compartido"), ("click", "Click en detalles")], max_length=20, verbose_name="Tipo de interaccion")),
                        ("timestamp", models.DateTimeField(auto_now_add=True, verbose_name="Fecha y hora")),
                        ("metadata", models.JSONField(blank=True, default=dict, verbose_name="Metadatos adicionales")),
                        ("job", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="user_interactions", to="jobs.jobs", verbose_name="Job")),
                    ],
                    options={
                        "verbose_name": "Interaccion con Job",
                        "verbose_name_plural": "Interacciones con Jobs",
                        "indexes": [
                            models.Index(fields=["user_identity_id", "timestamp"], name="jobs_jobint_user_ident_idx"),
                            models.Index(fields=["job", "interaction_type"], name="jobs_jobint_job_type_idx"),
                            models.Index(fields=["timestamp"], name="jobs_jobint_ts_idx"),
                        ],
                        "unique_together": {("user_identity_id", "job", "interaction_type")},
                    },
                ),
            ],
        ),
    ]
