name: Feature / Tarea
description: Proponer nueva funcionalidad o tarea a implementar
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Descripción
      description: Qué se necesita y por qué
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Criterio de aceptación
      description: Cómo se sabe que está terminado
      placeholder: |
        - [ ]
        - [ ]
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Notas adicionales
    validations:
      required: false
