# Generated by Django 5.0.1 on 2025-07-02 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('concensus', '0001_initial'),
        ('custom_auth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consensusresult',
            name='idGroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_auth.group'),
        ),
        migrations.AddField(
            model_name='debate',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debates', to='custom_auth.group'),
        ),
        migrations.AddField(
            model_name='debateparticipant',
            name='debate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='concensus.debate'),
        ),
        migrations.AddField(
            model_name='debateparticipant',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='finaltopicorder',
            name='idGroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_auth.group'),
        ),
        migrations.AddField(
            model_name='finaltopicorder',
            name='idUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='debate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='concensus.debate'),
        ),
        migrations.AddField(
            model_name='message',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='custom_auth.group'),
        ),
        migrations.AddField(
            model_name='message',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='concensus.message'),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationphaseone',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_auth.group'),
        ),
        migrations.AddField(
            model_name='notificationphaseone',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationphasetwo',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_auth.group'),
        ),
        migrations.AddField(
            model_name='notificationphasetwo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reaction',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='concensus.message'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recommendedtopic',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_topics', to='custom_auth.group'),
        ),
        migrations.AddField(
            model_name='finaltopicorder',
            name='idTopic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concensus.recommendedtopic'),
        ),
        migrations.AddField(
            model_name='consensusresult',
            name='idTopic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concensus.recommendedtopic'),
        ),
        migrations.AddField(
            model_name='topic',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concensus.group'),
        ),
        migrations.AddField(
            model_name='topicaddeduser',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_topics', to='custom_auth.group'),
        ),
        migrations.AddField(
            model_name='topicaddeduser',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_by_users', to='concensus.recommendedtopic'),
        ),
        migrations.AddField(
            model_name='topicaddeduser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_topics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userexpertise',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_auth.group'),
        ),
        migrations.AddField(
            model_name='userexpertise',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concensus.recommendedtopic'),
        ),
        migrations.AddField(
            model_name='userexpertise',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userphase',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_auth.group'),
        ),
        migrations.AddField(
            model_name='userphase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userposture',
            name='debate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postures', to='concensus.debate'),
        ),
        migrations.AddField(
            model_name='userposture',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersatisfaction',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_auth.group'),
        ),
        migrations.AddField(
            model_name='usersatisfaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='reaction',
            unique_together={('user', 'message')},
        ),
        migrations.AlterUniqueTogether(
            name='finaltopicorder',
            unique_together={('idGroup', 'idUser', 'idTopic')},
        ),
        migrations.AlterUniqueTogether(
            name='userexpertise',
            unique_together={('user', 'group', 'topic')},
        ),
        migrations.AlterUniqueTogether(
            name='userposture',
            unique_together={('user', 'debate')},
        ),
        migrations.AlterUniqueTogether(
            name='usersatisfaction',
            unique_together={('user', 'group')},
        ),
    ]
