# Generated by Django 5.0.1 on 2024-07-09 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concensus', '0004_alter_notificationphasetwo_notification_type_and_more'),
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsensusResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_value', models.FloatField()),
                ('idGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_auth.group')),
                ('idTopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concensus.recommendedtopic')),
            ],
        ),
    ]
