# Generated by Django 5.0.1 on 2024-07-10 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concensus', '0005_consensusresult'),
        ('custom_auth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSatisfaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satisfaction_level', models.CharField(choices=[('Unsatisfied', 'Unsatisfied'), ('Slightly Unsatisfied', 'Slightly Unsatisfied'), ('Neutral', 'Neutral'), ('Slightly Satisfied', 'Slightly Satisfied'), ('Satisfied', 'Satisfied')], max_length=20)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_auth.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'group')},
            },
        ),
    ]
