# Generated by Django 5.0.1 on 2024-07-10 14:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concensus', '0006_usersatisfaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersatisfaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
