# Generated by Django 5.0.1 on 2024-07-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concensus', '0007_usersatisfaction_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersatisfaction',
            name='message',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
