# Generated by Django 5.0.1 on 2024-07-10 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concensus', '0008_usersatisfaction_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersatisfaction',
            old_name='message',
            new_name='notification_message',
        ),
    ]
