# Generated by Django 5.0.1 on 2024-07-10 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concensus', '0009_rename_message_usersatisfaction_notification_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersatisfaction',
            old_name='notification_message',
            new_name='message',
        ),
    ]
