# Generated by Django 5.0.1 on 2024-06-11 19:47

import apps.custom_auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='apps/media/profile_pictures/default_profile_picture.png', null=True, upload_to=apps.custom_auth.models.get_profile_picture_filepath),
        ),
    ]
