# Generated by Django 5.0.1 on 2025-07-03 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_magiclink'),
        ('custom_auth', '0003_magiclink'),
    ]

    operations = [
    ]
